/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServerTrafficDto } from './serverTrafficDto';
import { TrafficBucketDto } from './trafficBucketDto';
import { RecentConnectionDto } from './recentConnectionDto';
import { RejectionDto } from './rejectionDto';
import { WakeStatsDto } from './wakeStatsDto';


export interface ConnectionStatsDto { 
    sinceUtc: string;
    activeNow: number;
    peakConcurrent: number;
    totalConnections: number;
    uniqueAddresses: number;
    longestActiveSeconds: number | null;
    medianSessionSeconds: number | null;
    byServer: Array<ServerTrafficDto>;
    traffic: Array<TrafficBucketDto>;
    wakes: WakeStatsDto;
    recent: Array<RecentConnectionDto>;
    rejections: Array<RejectionDto>;
}

