/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateServerDto { 
    serverType: string;
    displayName: string;
    hostname: string;
    memory: string;
    version?: string | null;
    modpackRef?: string | null;
    javaVersion?: string | null;
    useAikarFlags?: boolean;
    allowAnyClientVersion?: boolean;
    jvmArgs?: string | null;
    extraEnv?: string | null;
}

