/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HostResourcesDto { 
    totalMemoryBytes: number;
    allocatedMemoryBytes: number;
    availableMemoryBytes: number;
}

