/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecentConnectionDto { 
    serverName: string;
    playerName?: string | null;
    openedAt: string;
    durationSeconds: number;
}

