/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServerInstanceDtoMemoryBytes } from './serverInstanceDtoMemoryBytes';
import { ProblemDetailsStatus } from './problemDetailsStatus';
import { PlayerListDtoOnline } from './playerListDtoOnline';


export interface ServerInstanceDto { 
    id: string;
    serverType: string;
    version?: string | null;
    previousVersion?: string | null;
    modpackRef?: string | null;
    memory: string;
    javaVersion?: string | null;
    useAikarFlags: boolean;
    jvmArgs?: string | null;
    extraEnv?: string | null;
    displayName: string;
    hostname: string;
    port: PlayerListDtoOnline;
    containerName?: string | null;
    isManaged: boolean;
    isPublic: boolean;
    state?: string | null;
    isConfigManaged: boolean;
    nodeId?: string | null;
    playersOnline?: ProblemDetailsStatus | null;
    playersMax?: ProblemDetailsStatus | null;
    memoryBytes?: ServerInstanceDtoMemoryBytes | null;
    hasIcon: boolean;
    createdAt: string;
}

