/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardStatsDtoTotalInstances } from './dashboardStatsDtoTotalInstances';


export interface ServerInstanceDto { 
    id: string;
    serverType: string;
    version?: string | null;
    previousVersion?: string | null;
    modpackRef?: string | null;
    memory: string;
    displayName: string;
    hostname: string;
    port: DashboardStatsDtoTotalInstances;
    containerName?: string | null;
    isManaged: boolean;
    isPublic: boolean;
    state?: string | null;
    isConfigManaged: boolean;
    nodeId?: string | null;
    createdAt: string;
}

