/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServerPropertiesDto { 
    available: boolean;
    motd?: string;
    maxPlayers?: number;
    difficulty?: string;
    gamemode?: string;
    pvp?: boolean;
    onlineMode?: boolean;
    whitelist?: boolean;
    hardcore?: boolean;
    allowFlight?: boolean;
    enableCommandBlock?: boolean;
    viewDistance?: number;
    spawnProtection?: number;
}

