/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServerInstanceDto { 
    id: string;
    serverType: string;
    version?: string | null;
    modpackRef?: string | null;
    memory: string;
    javaVersion?: string | null;
    useAikarFlags: boolean;
    allowAnyClientVersion: boolean;
    jvmArgs?: string | null;
    extraEnv?: string | null;
    displayName: string;
    hostname: string;
    port: number;
    containerName?: string | null;
    isManaged: boolean;
    isPublic: boolean;
    lanPort?: number | null;
    lanBindAddress?: string | null;
    routedThroughProxy?: boolean;
    state?: string | null;
    isConfigManaged: boolean;
    playersOnline?: number | null;
    playersMax?: number | null;
    memoryBytes?: number | null;
    hasIcon: boolean;
    wakeOnConnect: boolean;
    wakeQueueSeconds: number;
    autoSleepEnabled: boolean;
    autoSleepIdleMinutes: number;
    createdAt: string;
}

