/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ServerStatsDto { 
    state?: string | null;
    cpuPercent?: number | null;
    memoryBytes?: number | null;
    memoryLimitBytes?: number | null;
    startedAt?: string | null;
    runningVersion?: string | null;
    motd?: string | null;
    playersOnline?: number | null;
    playersMax?: number | null;
}

