/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServerInstanceDtoMemoryBytes } from './serverInstanceDtoMemoryBytes';
import { ProblemDetailsStatus } from './problemDetailsStatus';
import { ServerStatsDtoCpuPercent } from './serverStatsDtoCpuPercent';


export interface ServerStatsDto { 
    state?: string | null;
    cpuPercent?: ServerStatsDtoCpuPercent | null;
    memoryBytes?: ServerInstanceDtoMemoryBytes | null;
    memoryLimitBytes?: ServerInstanceDtoMemoryBytes | null;
    startedAt?: string | null;
    runningVersion?: string | null;
    motd?: string | null;
    playersOnline?: ProblemDetailsStatus | null;
    playersMax?: ProblemDetailsStatus | null;
}

