/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerListDtoOnline } from './playerListDtoOnline';


export interface UpdateWakeDto { 
    wakeOnConnect: boolean;
    wakeQueueSeconds?: PlayerListDtoOnline;
}

