/**
 * CommandBlock.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WakeStatsDto { 
    total: number;
    failed: number;
    medianSeconds: number | null;
    p95Seconds: number | null;
    slowestSeconds: number | null;
}

