export * from './activity.service';
import { ActivityService } from './activity.service';
export * from './app.service';
import { AppService } from './app.service';
export * from './domains.service';
import { DomainsService } from './domains.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './host.service';
import { HostService } from './host.service';
export * from './minecraftVersions.service';
import { MinecraftVersionsService } from './minecraftVersions.service';
export * from './modpacks.service';
import { ModpacksService } from './modpacks.service';
export * from './server.service';
import { ServerService } from './server.service';
export const APIS = [ActivityService, AppService, DomainsService, FilesService, HostService, MinecraftVersionsService, ModpacksService, ServerService];
